### ISSUE TITLE
Mixins and breakpoints

### ISSUE THREAD

**Issue by chrisdarke42** [psu-libraries/psulib_base#11]
We need to plan what mixins and breakpoints are to be used

Next steps:
1. Define what breakpoints should be used across the sites by default
2. Define what other mixins might be beneficial to have on all sites
3. Propose in comments 
4. Discuss with team
5. Implement in theme

**Comment by chrisdarke42** [comment]
@schwent to review breakpoints by 6th of March, so we can compare with other sites and determine what is needed in base theme

**Comment by schwent** [comment]
Not using custom mixins or breakpoints at this time.
