### ISSUE TITLE
Define layouts

### ISSUE THREAD

**Issue by chrisdarke42** [psu-libraries/psulib_base#13]
Defining layouts for the sites is a big task, but it needs to start somewhere!
Grid vs flex, older grid systems, inheriting something from bootstrap, there are quite a few options.

Next steps

1. Determine what are the basic layouts that most of the sites are using, including different regions
2. Propose a layout system that will cover the main layouts in comments
3. Discuss with team
4. Implement the core layout for html / page level elements

**Comment by schwent** [comment]
1. Regions:
  Above Page (for announcements and alerts)
  Header Right (branding)
  Header Left (search)
  Navigation 
  Above Content
  Breadcrumbs
  Below Breadcrumbs
  Sidebar First
  Content
  Sidebar Second
  Above Footer
  Footer

**Comment by schwent** [comment]
2. Layouts:
   html.html.twig
  header.html.twig
  page.html.twig
  region.html.twig
  footer.html.twig (may prefer to use a block for footer content due to frequent changes)

**Comment by schwent** [comment]
3. Breakpoints:

**Comment by chrisdarke42** [comment]
@schwent to review breakpoints by 6th of March, so we can compare with other sites and determine what is needed in base theme

**Comment by cjwetherington** [comment]
If it's at all helpful, ROAM uses old-fashioned media queries designed for full responsivity from 360 on up.  Major rules are below.  768, 992, and 1200 are the most recurring.

footer.css:
@media only screen and (max-width: 991px)
@media only screen and (max-width: 767px)

general.css:
@media only screen and (min-width: 768px)
@media only screen and (min-width: 992px)
@media only screen and (min-width: 1200px)

header.css:
@media only screen and (max-width: 537px)

menu.css:
@media only screen and (max-width: 767px)

node.css:
@media only screen and (max-width: 991px)
@media only screen and (max-width: 767px)
@media only screen and (max-width: 567px)
@media only screen and (max-width: 411px)

search.css:
@media only screen and (max-width: 1199px)
@media only screen and (max-width: 991px)
@media only screen and (max-width: 767px)
@media only screen and (max-width: 677px)

views.css:
@media only screen and (max-width: 767px)

**Comment by chrisdarke42** [comment]
Looks like most of those are standards from bootstrap. A few of the others look like they are resulting from not doing mobile-first.
