### ISSUE TITLE
Basic theme header.

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/psulib_base#16]
- title
- menu
- search
- psu-icon

**Comment by chrisdarke42** [comment]
Review current headers of each of the sites to determine what can be reused and implemented in base theme

**Comment by cjwetherington** [comment]
For what it's worth, ROAM's header rules are here:  https://github.com/psu-libraries/roam/blob/main/web/themes/custom/roam_theme/css/header.css.  The header uses PSU colors, layout is float.
