### ISSUE TITLE
Improve Footer Layout Balance

### ISSUE THREAD

**Issue by cjwetherington** [psu-libraries/psulib_base#162]
Adding this rule seems to improve the layout balance on the psul-web footer:
`footer .container-fluid > div > div {
  flex: content;
}`

Before:
![image](https://github.com/user-attachments/assets/7a09fbe4-d7f1-43bb-a70a-fa790c885e24)

After:
![image](https://github.com/user-attachments/assets/a69b5153-130e-4ecd-a972-ecb3e2c045de)

**Comment by zipymonkey** [comment]
After looking at this the layout is intention.  It is built on bootstrap grid and.  The left section is 4 columns and the menu section is 8 columns.  That being said we can adjust the columns to be 3 and 9 on x-large displays.
