### ISSUE TITLE
Basic theme footer

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/psulib_base#17]
Add a basic footer and common design elements.  The common elements are:

- Penn State Logo
- Legal and Copyright statement 
- Contact and Address
- Footer

### University Libraries
- Penn State Libraries Logo
- Contact and Address
- footer menu
- Legal and Copyright statement
- Social Media links

### Hershey
-  Logos (PennState, PennStateHealth, College of Medicine)
- Contact and Address
- Legal and Copyright statement 

### Policies
- Penn State Logo
- Legal and Copyright statement 
- Footer menu

**Comment by cjwetherington** [comment]
For what it's worth, ROAM's styling rules are here: https://github.com/psu-libraries/roam/blob/main/web/themes/custom/roam_theme/css/footer.css.  It uses PSU approved colors and fonts (excepting the social icons).
