### ISSUE TITLE
Javascript compiling

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/psulib_base#18]
I'm not sure how to proceed, but I'm going to start the conversation 

I presume we would want something like 

```
mix.js('src/application.js', 'js');
```

in the webpack.mix.js file 
and then put our javavascripts in `src/application.js` ?
add this to our libraries file?

- [ ] how does cache busting work since our app presumably won't have laravel mix available to it? or will it?
- [ ] can we import other javascripts in application.js like we do with css, or will we need to give mix.js an array of javascripts? 

https://laravel-mix.com/docs/6.0/mixjs

**Comment by whereismyjetpack** [comment]
@chrisdarke42

**Comment by chrisdarke42** [comment]
All JS to be used on the site needs to be routed through the libraries.yaml
For that purpose it is best to have a 'base' js file (scripts.js or similar name) that is applied to the base theme globally. This is currently being accomplished with 'psulib_base.global.js'.
Another JS file could be added in as another library entry, eg:

`link_hover_widget:
  version: VERSION
  js:
    js/link_hover_2.js: {}`

Libraries are what also help deal with caching: https://chromatichq.com/insights/drupal-libraries-version/#:~:text=Library%20Version%20%26%20Caching,could%20not%20be%20more%20important.

You can also aggregate some files in a dir together such as :

`mix.combine('path/to/dir', 'all-files.js');`

so you could have a dir like /js/base and have all of that dir be converted into base.js
