### ISSUE TITLE
Menu is wrapping on very large screens

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#214]
this happens when I expand the page full width on my screen, it is flexing the main menu div next to the header.. noticed it on dsf..

![Screenshot 2024-11-20 at 15 38 02](https://github.com/user-attachments/assets/d021f51a-21e0-4519-b345-d27019ce267a)

**Comment by zipymonkey** [comment]
Reported by @chrisdarke42

**Comment by chrisdarke42** [comment]
Please review, thanks!
