### ISSUE TITLE
Intial tasks

### ISSUE THREAD

**Issue by chrisdarke42** [psu-libraries/psulib_base#3]
- [x] Set up laravel mix to compile assets for this as a base theme which can run in its own right
- [x] Set up README.md to document what this theme is to be used for
- [x] Document how to use base theme
- [x] Set up INSTALL.md for how to run the tooling

We need to define what are the elements that need to be native to this base theme, vs to the site themes.

**Comment by chrisdarke42** [comment]
@whereismyjetpack can you set up that Install.md? thanks!

**Comment by whereismyjetpack** [comment]
Install should be covered by https://github.com/psu-libraries/psulib_base/pull/26

**Comment by schwent** [comment]
Tasks done or in progress.
