### ISSUE TITLE
theme_wrapper tooling

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/psulib_base#5]
create workflow for working on the theme 

- clone bare template repository into 

- clone psulib_base into theme folder 
- remove old psulib_base

- instructions for use

**Comment by chrisdarke42** [comment]
remove old psulib_base

**Comment by chrisdarke42** [comment]
two tasks after this:
1. building the base theme - core elements
2. building the example sub theme

**Comment by chrisdarke42** [comment]
@whereismyjetpack https://stackoverflow.com/questions/57426306/ddev-mount-additional-folders-for-shared-composer-packages/57432155#57432155

**Comment by whereismyjetpack** [comment]
I think for now, using a bare-repository and developing like we did in co-working will be the least amount of friction, since that doesn't require extra docker-compose and mutagen configurations

**Comment by whereismyjetpack** [comment]
this should be resolved by https://github.com/psu-libraries/drupal-site-template/pull/26

**Comment by whereismyjetpack** [comment]
added readme, create ddev command to automate
