### ISSUE TITLE
Tooling to create child theme

### ISSUE THREAD

**Issue by chrisdarke42** [psu-libraries/psulib_base#8]
Need to define what is needed for child theme - 
Minimal would be information in the README about what files are needed.
A starterkit script would be great!

This depends on some theming to be completed on the base theme to experiment with.

**Comment by whereismyjetpack** [comment]
this should be resolved by https://github.com/psu-libraries/drupal-site-template/pull/26

**Comment by chrisdarke42** [comment]
Add some non-relative paths so that it can be run from different entry points, this caused an issue when run from within the theme folder.

**Comment by chrisdarke42** [comment]
Thanks for that, this is ready for release
